server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: ubuntu
    password: ubuntu
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
